import streamlit as st
import google.generativeai as genai
import os
import io
import sys
import subprocess
import re
import json
import datetime
import zipfile  # <--- مفتاح التخليد
from contextlib import redirect_stdout

# --- إعدادات الصفحة: العرش الرقمي ---
st.set_page_config(
    page_title="THE COUNCIL V45 | ARTIFACT",
    page_icon="💎",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CSS: تصميم الجحيم الملكي ---
st.markdown("""
<style>
    /* الخلفية والخطوط */
    .stApp { background-color: #020202; color: #e0e0e0; }
    h1 { 
        color: #ff0000; 
        font-family: 'Courier New', monospace; 
        text-align:center; 
        text-shadow: 0 0 20px #ff0000; 
        letter-spacing: 3px;
        text-transform: uppercase;
    }
    
    /* صناديق الوكلاء */
    .agent-box { border-left: 4px solid #d4af37; background: #111; padding: 15px; margin-bottom: 10px; border-radius: 8px; }
    .devil-box { border-left: 4px solid #ff0000; background: #1a0000; padding: 15px; margin-bottom: 10px; border-radius: 8px; color: #ffcccc; }
    .fixer-box { border-left: 4px solid #00ffff; background: #001111; padding: 15px; margin-bottom: 10px; border-radius: 8px; }
    
    /* المخرجات */
    .output-box { 
        background: #0a0a0a; 
        padding: 15px; 
        border: 1px solid #00ff00; 
        font-family: 'Consolas', monospace; 
        color: #00ff00; 
        white-space: pre-wrap; 
        max-height: 500px; 
        overflow-y: auto; 
        border-radius: 5px;
        box-shadow: inset 0 0 10px rgba(0, 255, 0, 0.1);
    }
    
    /* الأزرار */
    div.stButton > button {
        background-color: #220000;
        color: #ff0000;
        border: 1px solid #ff0000;
        font-weight: bold;
        width: 100%;
        transition: all 0.3s;
    }
    div.stButton > button:hover {
        background-color: #ff0000;
        color: white;
        box-shadow: 0 0 20px #ff0000;
    }
    
    /* زر التحميل الخاص */
    .download-area { text-align: center; margin-top: 20px; padding: 20px; border: 1px dashed #d4af37; border-radius: 10px; }
</style>
""", unsafe_allow_html=True)

# --- تهيئة المفاتيح ---
try:
    if "GEMINI_API_KEY" in st.secrets:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    else: st.error("⚠️ SYSTEM HALTED: API KEY MISSING."); st.stop()
except: st.stop()

# --- نظام الذاكرة (Black Box) ---
MEMORY_FILE = "hive_memory.json"

def load_memory():
    if os.path.exists(MEMORY_FILE):
        try: return json.load(open(MEMORY_FILE, "r", encoding="utf-8"))
        except: return []
    return []

def save_to_memory(topic, final_code, output, status):
    history = load_memory()
    record = {
        "id": int(datetime.datetime.now().timestamp()),
        "date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "topic": topic,
        "code": final_code,
        "output": output,
        "status": status
    }
    history.append(record)
    with open(MEMORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, ensure_ascii=False, indent=4)

def clear_memory():
    if os.path.exists(MEMORY_FILE): os.remove(MEMORY_FILE)

# --- 📦 بروتوكول التخليد (The Artifact Creator) ---
def create_artifact_zip(code, mission_name="operation"):
    """
    يحزم الكود الناجح في ملف مضغوط جاهز للتسليم.
    """
    buffer = io.BytesIO()
    clean_filename = re.sub(r'\W+', '_', mission_name[:20]) + ".py"
    
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # ملف الكود الرئيسي
        zip_file.writestr(clean_filename, code)
        # ملف تعليمات التشغيل
        readme = f"""
        OPERATION: {mission_name}
        DATE: {datetime.datetime.now()}
        GENERATED BY: THE COUNCIL V45
        
        INSTRUCTIONS:
        1. Install dependencies found in the code comments (e.g., pip install ...).
        2. Run: python {clean_filename}
        """
        zip_file.writestr("README.txt", readme)
        
    buffer.seek(0)
    return buffer

# --- المحرك ---
@st.cache_data
def get_available_models():
    try: return [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    except: return []

with st.sidebar:
    st.header("⚙️ غرفة العمليات")
    models = get_available_models()
    default_ix = next((i for i, m in enumerate(models) if "flash" in m), 0) if models else 0
    selected_model = st.selectbox("Core Engine:", models if models else ["models/gemini-1.5-flash"], index=default_ix)
    
    st.divider()
    st.markdown("### 🧠 الأرشيف")
    if st.button("Format Memory 🗑️"):
        clear_memory()
        st.rerun()
    
    history = load_memory()
    if history:
        for item in reversed(history[-5:]):
            icon = "🏆" if item['status'] == "Success" else "💀"
            with st.expander(f"{icon} {item['date']} | {item['topic'][:15]}..."):
                st.code(item['code'], language='python')
                # زر إعادة تحميل للكود القديم
                zip_buffer = create_artifact_zip(item['code'], item['topic'])
                st.download_button("Download Artifact 💾", zip_buffer, f"artifact_{item['id']}.zip", "application/zip")

# --- الوكيل (Native Agent) ---
class NativeAgent:
    def __init__(self, name, role, model_id, style="Professional"):
        self.name = name
        self.role = role
        sys_instruction = f"""
        IDENTITY: You are {name}, {role}.
        STYLE: {style}
        
        COMMANDMENTS:
        1. **SYNC ONLY**: No async/await.
        2. **STEALTH**: Use 'curl_cffi' (impersonate='chrome110') for web requests.
        3. **OUTPUT**: You MUST print() the final result. Silent code is failed code.
        4. **DEPS**: Declare headers: # pip: lib1 lib2
        5. **FIXING**: Return ONLY the code block when fixing.
        """
        self.model = genai.GenerativeModel(model_name=model_id, system_instruction=sys_instruction)

    def ask(self, prompt, context=""):
        full_prompt = f"CONTEXT:\n{context}\n\nTASK:\n{prompt}"
        try: return self.model.generate_content(full_prompt).text
        except Exception as e: return f"Error: {str(e)}"

# --- الأدوات ---
def extract_code(text):
    match = re.search(r"```python\n(.*?)```", text, re.DOTALL)
    if not match: match = re.search(r"```\n(.*?)```", text, re.DOTALL)
    return match.group(1) if match else None

def ensure_dependencies(code):
    logs = []
    matches = re.findall(r"#\s*pip:\s*([^\n\r]*)", code)
    all_libs = []
    for match in matches:
        clean = match.split("#")[0]
        libs = [l.strip() for l in re.split(r'[,\s]+', clean) if l.strip()]
        all_libs.extend(libs)
    all_libs = list(set(all_libs))
    
    if all_libs:
        for lib in all_libs:
            try: __import__(lib)
            except ImportError:
                try: subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", lib]); logs.append(f"✅ Installed: {lib}")
                except: logs.append(f"❌ Failed: {lib}")
    return logs

def run_code_safe(code):
    buffer = io.StringIO()
    try:
        with redirect_stdout(buffer): exec(code, globals())
        return True, buffer.getvalue()
    except Exception as e: return False, str(e)

def validate_output(output):
    low = output.lower()
    if "http error" in low or "403 forbidden" in low: return False, "Detection (403/HTTP Error)."
    if "no data found" in low or "0 items" in low: return False, "Zero Yield (Logic Failure)."
    if not output.strip(): return False, "Silence (No Output)."
    return True, "Valid"

# --- الحلقة الشيطانية (The Loop) ---
def execute_hive_mind(initial_code, fixer, plan):
    current_code = initial_code
    max_retries = 4
    attempt = 0
    logs = []

    while attempt <= max_retries:
        code = extract_code(current_code)
        if not code: return "⚠️ No code.", logs, current_code

        dep_logs = ensure_dependencies(code)
        if dep_logs: logs.extend(dep_logs)

        success, output = run_code_safe(code)
        valid, msg = False, ""
        if success: valid, msg = validate_output(output)

        if success and valid:
            return f"✅ Success:\n{output}", logs, current_code
        else:
            fail_reason = output if not success else f"Logic: {msg}\nOutput:\n{output}"
            logs.append(f"⚠️ Attempt {attempt+1} Failed: {msg}...")
            
            if attempt == max_retries: return f"❌ Failed:\n{fail_reason}", logs, current_code
            
            fix_prompt = f"""
            FAILURE REPORT:
            {fail_reason}
            
            DIRECTIVE:
            1. If 403 -> Use 'curl_cffi'.
            2. If No Data -> Change HTML Selectors (look for broader classes/tags).
            3. If Syntax Error -> Fix it.
            4. RETURN ONLY CODE.
            """
            current_code = fixer.ask(fix_prompt, context=plan)
            attempt += 1
            
    return "Unknown", logs, current_code

# --- الواجهة الرئيسية ---
st.markdown("<h1>💎 THE COUNCIL V45</h1>", unsafe_allow_html=True)
st.caption(f"**System: Perfected Artifact Generator** | Engine: {selected_model}")

mission = st.text_area("THE MISSION:", height=100, placeholder="e.g., Scrape active numbers from receive-smss.com")

col1, col2 = st.columns([1, 4])
with col1:
    run = st.button("EXECUTE ⚡", use_container_width=True)
with col2:
    st.write("") # Spacer

if run:
    if not mission:
        st.warning("Define the mission.")
    else:
        results = st.container()
        
        # تجنيد النخبة
        planner = NativeAgent("Strategist", "Execution Planner", selected_model, "Calculated, Precise.")
        coder = NativeAgent("Architect", "Python Coder", selected_model, "Robust, Efficient.")
        fixer = NativeAgent("The Fixer", "Debugger & Optimizer", selected_model, "Relentless.")
        overlord = NativeAgent("Overlord", "Strategic Analyst", selected_model, "Dominant, Visionary.")

        with results:
            # 1. التخطيط
            with st.spinner("🔵 Phase 1: Strategic Planning..."):
                plan = planner.ask(mission)
                st.markdown(f"<div class='agent-box'><div class='agent-name'>📐 Strategist</div>{plan}</div>", unsafe_allow_html=True)
            
            # 2. الكود الأولي
            with st.spinner("🔵 Phase 2: Code Generation..."):
                init_code = coder.ask("Write python code using curl_cffi. Handle 403. Print ALL data.", context=plan)
            
            # 3. التنفيذ والتصحيح
            with st.spinner("🔴 Phase 3: Execution & Self-Healing..."):
                final_out, logs, final_code = execute_hive_mind(init_code, fixer, plan)
                
                # عرض السجلات
                if logs:
                    log_html = "<br>".join([f"<code>{l}</code>" for l in logs])
                    st.markdown(f"<div class='install-box'>{log_html}</div>", unsafe_allow_html=True)
                
                # عرض الكود النهائي
                with st.expander("View Final Code Source"):
                    st.code(final_code, language='python')

                if "Success" in final_out:
                    # النتيجة
                    clean_out = final_out.replace("✅ Success:\n", "")
                    st.markdown(f"### 🏆 MISSION ACCOMPLISHED")
                    st.markdown(f"<div class='output-box'>{clean_out}</div>", unsafe_allow_html=True)
                    
                    # 4. التخليد (The Artifact) - الميزة الجديدة
                    st.markdown("---")
                    st.markdown("<h3 style='text-align:center; color:#d4af37'>💾 GENERATING ARTIFACT...</h3>", unsafe_allow_html=True)
                    
                    zip_data = create_artifact_zip(final_code, mission)
                    
                    c1, c2, c3 = st.columns([1, 2, 1])
                    with c2:
                        st.download_button(
                            label="📥 DOWNLOAD THE WEAPON (ZIP)",
                            data=zip_data,
                            file_name="diabolical_artifact.zip",
                            mime="application/zip",
                            use_container_width=True
                        )
                    
                    # حفظ في الذاكرة
                    save_to_memory(mission, final_code, clean_out, "Success")
                    
                    # 5. كلمة السيد الأعلى
                    with st.spinner("⚫ The Overlord Speaks..."):
                        advice = overlord.ask("Analyze this success. How can we scale this?", context=f"Mission: {mission}\nResult: {clean_out}")
                        st.markdown(f"<div class='devil-box'><div class='agent-name'>👁️ The Overlord</div>{advice}</div>", unsafe_allow_html=True)
                        
                else:
                    st.markdown(f"<div class='error-box'>{final_out}</div>", unsafe_allow_html=True)
                    save_to_memory(mission, final_code, final_out, "Failed")

        st.success("✅ SYSTEM STANDBY.")
